### ISSUE TITLE
incorrect YAML newlines for frontmatter values of type list

### ISSUE THREAD

**Issue by reedtaylor** [cloud-atlas-ai/obsidian-am#47]
If the Amazing Marvin value for a `[key,value]` pair has a list type in the `value`, the YAML output does correctly format the YAML for that list, but then this is grafted into a string representation that isn't correct and doesn't get parsed properly by Obsidian.

For example aproject with two different tags in Marvin generates the following nonparsed frontmatter:
```yaml
---
_id: yPZpzJojxxxxxx

type: project

title: fix the deck heaters

parentId: 39f16d7b-be4b-4745-bd3f-xxxxxxxx

labelIds: - BhL8ruskRsbf2       ###  PROBLEMATIC
- JXghRsz3KqFsM

deepLink: https://app.amazingmarvin.com/#p=xxxxxxxxxx

---
```
The issue stems from the "labelIds" key, whose value has newlines in the wrong spots.  If modified to look like the following, then everything parses correctly:
```yaml
labelIds: 
- BhL8ruskRsbf2
- JXghRsz3KqFsM
````

The underlying cause seems to be the simple string format being applied to combine the key and value [here](https://github.com/cloud-atlas-ai/obsidian-am/blob/0d2abf5be1713442b62d3239e95be2ca81ba2cf8/src/main.ts#L550).  I believe this same line is the cause for #43 .

A suggested fix might be to create a local, standalone key-value pair from the key and value, and ask the YAML formatter to stringify that object as a whole.  (I would try to create a PR myself but I'm concerned I might not find time very soon.)
